# Generated by Django 3.0.3 on 2020-02-24 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('slug', models.SlugField()),
                ('date_of_creation', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'tag',
                'verbose_name_plural': 'tags',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('slug', models.SlugField()),
                ('description', models.TextField()),
                ('date_of_creation', models.DateTimeField(auto_now=True)),
                ('start_time', models.DateTimeField()),
                ('deadline', models.DateTimeField()),
                ('tags', models.ManyToManyField(related_name='tasks', to='task_manager.Tag')),
            ],
            options={
                'verbose_name': 'task',
                'verbose_name_plural': 'tasks',
                'ordering': ('start_time', 'deadline', 'date_of_creation'),
            },
        ),
    ]
