# Generated by Django 3.0.3 on 2020-02-25 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0003_auto_20200225_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date_of_creation',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
