# Generated by Django 3.0.3 on 2020-02-27 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0008_auto_20200225_1738'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='user',
        ),
    ]
